# This is a basic workflow to help you get started with Actions

name: "Birth Alert Bot"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the bot branch
on:
  push:
    branches: [ master ]
  schedule:
    # 01 + 8
    - cron: '0 1 * * *'
    
  # 手动触发事件
  workflow_dispatch:
    inputs:
      dispatch:
        description: 'Test dispatch'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          python-version: 14.x

      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          npm install

      - name: Working
        env:
          SERVERCHAN_SECRETKEY: ${{ secrets.SERVERCHAN_SECRETKEY }}
          BIRTH_DATA: ${{ secrets.BIRTH_DATA }}
        run: node index.js